# Generated by Django 4.1.2 on 2022-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='artist_picture'),
        ),
    ]
