# Generated by Django 4.1.2 on 2022-10-29 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(default='album_logo.jpg', upload_to='album_logo_picture', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist', verbose_name='band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='posted_date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='producer',
            field=models.CharField(max_length=100, verbose_name='producer'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='released_date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
    ]
