# Generated by Django 4.1.2 on 2022-11-02 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['slug'], name='music_album_slug_eeb8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['slug'], name='music_artis_slug_38018e_idx'),
        ),
    ]
