# Generated by Django 4.1.2 on 2022-11-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_slug_artist_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
    ]
