# Generated by Django 3.2 on 2022-11-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myplaylist',
            old_name='album_id',
            new_name='song_id',
        ),
    ]
